version: '3.8'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
    volumes:
      - ./database-data:/data/db

  spring_app:
    build: ./backend
    container_name: spring_app
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://root:password@mongodb:27017/yourdbname?authSource=admin
    depends_on:
      - mongodb
    volumes:
      - .:/app
      - /app/target

  react_app:
    build: ./frontend
    container_name: react_app
    ports:
      - "3000:80"
    depends_on:
      - spring_app
